services:
  vaulty:
    build: .
    container_name: vaulty-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - DB_PATH=/usr/src/app/data/vaulty.db
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
